# Generated by Django 2.0 on 2017-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0006_books_avgrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='avgrate',
            field=models.FloatField(default=0.0),
        ),
    ]
